server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-cartao
              uri: http://ms-cartao:8081
              predicates:
                - Path=/api/cartoes/**

            - id: ms-cliente
              uri: http://ms-cliente:8082
              predicates:
                - Path=/api/clientes/**

            - id: ms-auth
              uri: http://ms-auth:8084
              predicates:
                - Path=/api/auth/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

jwt:
  secret: mySecretKeyForJWTGenerationThatIsAtLeast32BytesLong
  public-paths:
    - /api/auth/login
    - /api/auth/register
    - /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always